"""그래프 실행 한도와 공통 시간 초과입니다."""

BRIEF_STEPS = 3
CONSULT_STEPS = 5
EVALUATOR_RESERVE = 4
INITIAL_CONSULT_ROUNDS = 2
EVALUATION_CONSULT_ROUNDS = 4
MIN_EXPERT_CALLS = 3
QUESTION_SUMMARY_LENGTH = 300
RECURSION_LIMIT = 32
DEFAULT_AGENT_TIMEOUT = 180.0
